docker-build:
  stage: build
  only:
   - main
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE: registry.gitlab.com/sistema-prefeitura/back-pomar-domestico
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE
